version: "3.7"
networks:
  app-network:
    driver: bridge

services:
  database:
    image: postgres:11.0-alpine
    networks:
      - app-network
    environment:
      DEBUG: 'false'
    env_file:
      - .env
    ports:
      - 5432:5432
